### ISSUE TITLE
Facade style API change proposal

### ISSUE THREAD

**Issue by bbankowski** [Danon/CleanRegex#1]
For Facade style, instead of:
```php
Pattern::pattern('[A-Z][a-z]+')->matches($subject)
```

You could try:
```php
Pattern::of('[A-Z][a-z]+')->matches($subject)
```

Reads better for me :)

**Comment by Danonk** [comment]
gracias, amigo :+1:  I didn't like *pattern pattern* either :)

 (had no idea for a better name though)
